name: "Static code analysis"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install cppcheck
      run: |
        sudo apt update -y
        sudo apt install -y cppcheck

    - name: Check code
      run: |
        readarray -t files < <(find . -maxdepth 1 -type f \( -name "*.h" -o -name "*.cpp" \))
        cppcheck --check-level=exhaustive \
                 --enable=warning,performance,portability \
                 --error-exitcode=1 \
                 --force \
                 --inconclusive \
                 --language=c++ \
                 --std=c++11 \
                 -j $(nproc) \
                 "${files[@]}"
