name: "Unit Tests"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        standard: [11, 14, 17, 20, 23]
        compiler: ['g++', 'clang++']

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DWITH_TESTS=ON -DCMAKE_CXX_STANDARD=${{matrix.standard}} -DCMAKE_CXX_COMPILER=${{matrix.compiler}}

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . -j $(nproc)

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --rerun-failed --output-on-failure

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        standard: [11, 14, 17, 20, 23]

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DWITH_TESTS=ON -DCMAKE_CXX_STANDARD=${{matrix.standard}}

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . -j "$env:NUMBER_OF_PROCESSORS"

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --rerun-failed --output-on-failure

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        standard: [11, 14, 17, 20, 23]

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DWITH_TESTS=ON -DCMAKE_CXX_STANDARD=${{matrix.standard}}

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . -j $(nproc)

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --rerun-failed --output-on-failure
